//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHeelOfLifeApp.Models
{
		using System;
		using System.Collections.Generic;

		public partial class Categories: System.Object {
			[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
			public Categories() {
				this.Tasks = new HashSet<Tasks>();
			}

			public virtual AspNetUsers AspNetUsers { get; set; }

			public int Id { get; set; }

			public string Name { get; set; }

			public string Owner_Id { get; set; }

			[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
			public virtual ICollection<Tasks> Tasks { get; set; }
		}
}
